spring.application.name=XiaozhiAI
server.port=8080

#langchain4j.open-ai.chat-model.base-url=http://langchain4j.dev/demo/openai/v1
#langchain4j.open-ai.chat-model.api-key=demo
#langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
#
#langchain4j.open-ai.chat-model.log-requests=true
#langchain4j.open-ai.chat-model.log-responses=true


langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=gemma4:e2b
langchain4j.ollama.chat-model.temperature=0.8
langchain4j.ollama.chat-model.timeout=PT60S

langchain4j.community.dashscope.chat-model.base-url=https://ws-emz8vhhwn0w8hnun.ap-southeast-1.maas.aliyuncs.com/api/v1
langchain4j.community.dashscope.chat-model.api-key=${DASHSCOPE_API_KEY}
langchain4j.community.dashscope.chat-model.model-name=qwen-max

#集成阿里通义千问-流式输出
langchain4j.community.dashscope.streaming-chat-model.base-url=https://ws-emz8vhhwn0w8hnun.ap-southeast-1.maas.aliyuncs.com/api/v1
langchain4j.community.dashscope.streaming-chat-model.api-key=${DASHSCOPE_API_KEY}
langchain4j.community.dashscope.streaming-chat-model.model-name=qwen-plus

#集成阿里通义千问-通用文本向量-v3
langchain4j.community.dashscope.embedding-model.base-url=https://ws-emz8vhhwn0w8hnun.ap-southeast-1.maas.aliyuncs.com/api/v1
langchain4j.community.dashscope.embedding-model.api-key=${DASHSCOPE_API_KEY}
langchain4j.community.dashscope.embedding-model.model-name=text-embedding-v3

pinecone.api-key=${PINECONE_API_KEY}

#logging.level.root=debug


spring.data.mongodb.uri=mongodb://localhost:27017/chat_memory_db

# SQL data source
spring.datasource.url=jdbc:mysql://localhost:3306/xiaozhi?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Enable SQL log
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
